data_dir: "../data/wdc_normalized"
output_dir: "../results"
checkpoint_dir: "../checkpoints"

seed: 42
do_train: false
do_eval: true

logging_strategy: steps
logging_steps: 10
eval_strategy: epoch
save_strategy: epoch
save_total_limit: 3
metric_for_best_model: overall_average_f1_score
load_best_model_at_end: true
greater_is_better: true

optim: adamw_torch_fused
max_grad_norm: 1.0
lr_scheduler_type: constant
warmup_ratio: 0.1

bf16: false
fp16: false

per_device_train_batch_size: 8
per_device_eval_batch_size: 32
gradient_accumulation_steps: 1
