defaults:
  - base_config

paradigm: "generation"
model_name: "Qwen/Qwen2.5-7B-Instruct"

do_train: true
learning_rate: 1.0e-5
num_train_epochs: 3
per_device_train_batch_size: 4
per_device_eval_batch_size: 16
gradient_accumulation_steps: 2
weight_decay: 0.01

lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
lora_target_modules: [q_proj, k_proj, v_proj]

bf16: true 