defaults:
  - base_config

paradigm: "classification"
model_name: "FacebookAI/roberta-base"

do_train: true
learning_rate: 5.0e-5
num_train_epochs: 4.0
per_device_train_batch_size: 8
per_device_eval_batch_size: 16
threshold: 0.5
gradient_accumulation_steps: 1
weight_decay: 0.01
