defaults:
  - base_config

paradigm: "retrieval"
model_name: "FacebookAI/roberta-base"

do_train: true
learning_rate: 5.0e-5
num_train_epochs: 4.0
per_device_train_batch_size: 8
per_device_eval_batch_size: 16
gradient_accumulation_steps: 1
weight_decay: 0.01

# Retrieval specific parameters
projection_dim: 256
temperature: 0.05
num_samples: 128
